repos:
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.40.0
    hooks:
      - id: markdownlint
        name: Validate Markdown text

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        name: Makes sure files end in a newline and only a newline

      - id: check-merge-conflict
        name: Check for files that contain merge conflict strings

      - id: no-commit-to-branch
        name: Don't commit to main branch.
        args: [--branch, main]
        fail_fast: true

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.89.1
    hooks:
      - id: terraform_fmt
        name: Format Terraform code

      - id: terraform_validate
        name: Validate Terraform code
        exclude: ^(examples|tests)
        args:
          - --tf-init-args=-upgrade
          - --tf-init-args=-backend=false
          - --hook-config=--retry-once-with-cleanup=true

      - id: terraform_tflint
        name: Validate Terraform tests
        exclude: ^(examples|tests)
        args:
          - --args=--enable-rule=terraform_naming_convention
          - --args=--enable-rule=terraform_unused_required_providers
          - --args=--module

      - id: terraform_docs
        name: Generate Terraform documentation
